= Pflichtenheft MusicVoting
// Metadata
firstname lastname <mail@mail-server>
2.0, dd-mm-yyyy: Some notes

// Settings
:source-highlighter: coderay
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
// Refs:
:imagesdir: images
:sourcedir-code: src/main/java/at/htl/jdbcprimer
:sourcedir-test: src/test/java/at/htl/jdbcprimer
:toc:

Version: 2.0 +
//Version Date: {revdate} +
//Version Notes: / +
Author: Aigner Lara, Muratspahic Irfan, Schauflinger Hanna

++++
<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
++++


== Beschreibung der Ausgangssituation

Die HTBLA Leonding ist eine mittelgroße Schule im Zentralraum Oberösterreich.

== Istzustand

Jedes Jahr finden zahlreiche Veranstaltungen, Feste und Feierlichkeiten statt. Musik wird gespielt,
ganz egal welche Art von Veranstaltung stattfindet, Musik begleitet sie.

////
=== Beschreibung der Geschäftsprozesse

Aktivitätsdiagramm des Geschäftsprozesses 1 +
Aktivitätsdiagramm des Geschäftsprozesses 2 +
...
////

== Problemstellung

Es kann vorkommen, dass die Besucher/Teilnehmer etwaiger Veranstaltungen mit der Wahl des Musikstils bzw.
im Allgemeinen mit der Wahl der Songs unzufrieden sind. Bei fixen Playlisten tritt außerdem das Problem auf,
dass sich mit der Zeit die Songs wiederholen könnten. Ist keine vorgefertigte Playlist für das
Event vorhanden, muss jedoch selbst eine Playlist erstellt werden, welches widerum eine zeitintensive Arbeit ist.


== Aufgabenstellung

Es ist ein System zu Entwicklen bei dem sich Besucher mit ihrem Smartphone mittels QR-Code anmelden und somit Songs zu einer
Playlist hinzufügen können, diese Playlist ist für andere verbunde Teilnehmer einsehbar wobei
diese wiederum für Songs in dieser Playlist voten können oder ebenfalls eigene Songs hinzufügen können. Dies
geschieht über das Videoportal YouTube, welches eine große Bandbreite an Musikauswahl liefert. Die Benutzeroberfläche
für das Smartphone soll ebenfalls optimiert werden.

=== Funktionale Anforderungen

==== Anwendungsfalldiagramm (Use-Case-Diagram)

==== Use-Case 1

Ziel des Use Cases: Als User möchte ich ein Lied zur Playlist hinzufügen. +
Vorbedingung: User braucht ein Smartphone. +
Nachbedingung bei erfolgreicher Ausführung: Man muss mit dem richitgen WLan verbunden sein.

Beschreibung:

* mit WLan verbinden +
* richtige Webseite aufrufen +
* Song suchen +
* auf Plus drücken


Beteiligte Nutzer: Absolvente der HTL Leonding und Lehrer der HTL Leonding.

Auslösendes Ereignis: Wenn der User einen bestimmten Song hören will.


==== Use-Case 2
Ziel des Use Cases: Als User möchte ich ein Lied nach oben voten. +
Vorbedingung: User braucht ein Smartphone. +
Nachbedingung bei erfolgreicher Ausführung: Man muss mit dem richitgen WLan verbunden sein.

Beschreibung:

* mit WLan verbinden +
* richtige Webseite aufrufen +
* für Song voten

Beteiligte Nutzer: Absolvente der HTL Leonding und Lehrer der HTL Leonding.

Auslösendes Ereignis: Wenn dem User ein Lied, welches bereits in der Playlist ist, gefällt.


==== Use-Case 3
Ziel des Use Cases: Als Admin möchte ich ein Lied nicht hören. +
Vorbedingung: Admin muss auf einem Bildschirm laufen. +
Nachbedingung bei erfolgreicher Ausführung: Admin muss das Passwort wissen.

Beschreibung:

* Seite aufrufen +
* Anmelden +
* Song überspringen

Beteiligte Nutzer: Administrator der Applikation.

Auslösendes Ereignis: Wenn ein Lied nicht angebracht ist oder es dem Admin nicht gefällt.


==== Use-Case 4
Ziel des Use Cases: Als Admin möchte ich ein aus der Playlist löschen. +
Vorbedingung: Admin muss auf einem Bildschirm laufen. +
Nachbedingung bei erfolgreicher Ausführung: Admin muss das Passwort wissen.

Beschreibung:

* Seite aufrufen +
* Anmelden +
* Lied löschen

Beteiligte Nutzer: Administrator der Applikation.

Auslösendes Ereignis: Wenn ein Lied nicht angebracht ist oder es dem Admin nicht gefällt.

image::usecase(1).jpg[UseCaseDiagramm]

=== Nicht-funktionale Anforderungen
Benutzbarkeitsanforderung:
Die Applikation soll lauffähig sein.

Effizienzanforderung:
Lieder sollen in Echtzeit zur Playlist hinzugefügt werden und Playlist soll zeitgleich bei allen neu sortiert werden.

Wartbarkeits- und Portierbarkeitsanforderung:
Die Applikation soll später von Youtube streamen.

Sicherheitsanforderung:
Die Playlist soll immer up to date sein.

Gesetzliche Anforderung:
Die Applikation darf mp3 files nicht durchs öffentliche Netzwerk schicken.

== Zielsetzung

Im Rahmen dieser Veranstaltungen liegt es im Interesse der Besucher/Teilnehmer eine musikalische
Begleitung zu haben, die jedermanns Geschmack trifft. Daraus folgt gute Laute und ein Erfolgserlebnis
bei den Besuchern, unabhägig davon welche Art der Veranstaltung besucht wird.

== Mengengerüst
Die HTL Leonding hat jährlich bis zu 150 Absolventen. Noch dazu kommen einige Absolventen der vergangenen Jahre.
